[DB]
# Identifiants de connexion à l'historian Wonderware
db_host = VOTRE_SERVEUR
db_name = Runtime
odbc_driver = SQL Server
trusted_connection = no
db_user = VOTRE_UTILISATEUR
db_password = VOTRE_MOT_DE_PASSE

[Tags]
# Noms exacts des capteurs dans la base de données
vitesse = N1n2_VITCEN04
intensite = N1n2_ITCEN04
vibration = N1n2_VT_vibration_CEN04
debit_entree = L1_W_EAFT1005
pression_sortie = N1n2_PT4047

[Thresholds]
# Le saut brutal d'intensité qui déclenche l'enregistrement de l'événement
trigger_jump = 12.0
# Pic minimum pour valider un débourbage total
intensity_peak = 70.0
# ... (Gardez les autres seuils par défaut ici)
intensity_peak = 70.0
blue_peak_window = 4.0
flow_cutoff = 1.5
max_speed = 6000.0
min_speed = 5600.0
min_duration_sec = 3
max_duration_sec = 480
stop_threshold_h = 400
seuil_maintenance_h = 23
hysteresis_margin = 10.0
nep_burst_window_h = 3.0
nep_burst_min_events = 7

[Period]
start_time = 2025-01-19 00:00:00
end_time = 2026-02-22 23:59:59
